<a href="https://colab.research.google.com/github/yaseen-s-8547/AI-Journey/blob/master/WEEK1_AI_MATH_PLAYGROUND.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#THE_BASICS


#BASICS



[link text](https://)# New Section

In [ ]:
import numpy as np
a=np.array([1,2,3],dtype='int32')
print(a)
#here we are creating simple list,but turning in to a numpy array
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
#here we created a 2D array(matrixwith 2 rows and 3 coloumns)
#...............................................................
   #NOW LETS DISSECT THE PROPERTIES OF NUMPY ARRAYS

"""check dimension"""
print(a.ndim)
#a.ndim means to check dimensions of array
b.ndim
#dimension of the second array
#...............................................................
""" check rows and coloumns"""
print("shape: ",a.shape)
print("size of rows and coloumns:" ,b.shape)
#...............................................................
"""to know what kind of numbers stored"""
print(a.dtype)
print(b.dtype)
#...............................................................
"""To Know size of elements in bytes"""
print(a.itemsize)
print(b.itemsize)
#...............................................................
"""to know total memory in bytes"""
print(a.nbytes)
#...............................................................
"""Total Number of elements"""
print(a.size)
#...............................................................


[1 2 3]
1
shape:  (3,)
size of rows and coloumns: (2, 3)
int32
float64
4
8
12
3


Accessing/Changing speciifc elements,rows,columns etc


In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
#this is the array of 2 rows and 7 coloumns
#.....................................................
"""Access specific element"""
#syntax:a[row_index,column_index]
print(a[1,5])
#.....................................................
"""Access a full row"""
#syntax:a[row_index,:]
print(a[0,:])
#......................................................
"""Access a full column"""
#syntax:a[:,column_index]
print(a[:,2])
#......................................................
"""Fancy Slicing:Select with start:end:step"""
#syntax:a[row_index,start:end:step]
print(a[1,1:-1:3])
#.......................................................
"""change an elemnt"""
#syntax a[row_index,coloumn_index]
a[1,5]=20
print(a)
#........................................................
"""change a full column"""
a[:,2]=[1,2]
#here semi colon represents grabbing entire elements in the row
print(a)
#........................................................
"""3D example"""
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
#get specific element(work out side in)
print(c[1][1][1])
print(c[:,0,:])
#replacing
c[:,0,:]=[[9,9],[8,8]]
print(c)







[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[1 2 3 4 5 6 7]
[ 3 10]
[ 9 12]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
[[1 2]
 [5 6]]
[[[9 9]
  [3 4]]

 [[8 8]
  [7 8]]]


INITIALIZING DIFFERENT TYPES OF ARRAYS




In [14]:
import numpy as np
"""All ZEROS Matrix"""
print(np.zeros((4,2,5)))
print("...........................................")
#....................................
"""ALL ones"""
print(np.ones((4,2,4)))
print("...........................................")
#....................................
"""Matrix With Any Number"""
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(np.full((2,5,3),10))
print("...........................................")
print(np.full_like(a,4))
print("...........................................")
#....................................
"""Random Numbers"""
print(np.random.rand(4,2))
print("...........................................")
print (np.random.randint(-1,7,size=(3,3)))
print("...........................................")
#.....................................................
"""Identity Matrix"""
print(np.identity(5))
print(".............................................")
#......................................................
"""Repeat Array"""
arr=np.array([[1,2,3,5],[3,4,5,0],[5,6,7,0]])
print(np.repeat(arr,3,axis=0))
print("................................................")
#..........................................................
"""Matrix Puzzle (Embedding a smaller matrix in a bigger one)"""
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:-1,1:-1]=z
print(output)
print(".........................................")
#............................................................







[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
...........................................
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
...........................................
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[[10 10 10]
  [10 10 10]
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]
  [10 10 10]
  [10 10 10]]]
...........................................
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
...........................................
[[0.1047527  0.4488723 ]
 [0.66677827 0.79096322]
 [0.81943936 0.87026914]
 [0.84854815 0.33251781]]
...........................................
[[ 6  3  1]
 [-1 -1  2]
 [ 4  0  1]]
...........................................
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0