<a href="https://colab.research.google.com/github/yaseen-s-8547/AI-Journey/blob/master/WEEK1_AI_MATH_PLAYGROUND.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#THE_BASICS


#BASICS



In [ ]:
import numpy as np
a=np.array([1,2,3],dtype='int32')
print(a)
#here we are creating simple list,but turning in to a numpy array
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
#here we created a 2D array(matrixwith 2 rows and 3 coloumns)
#...............................................................
   #NOW LETS DISSECT THE PROPERTIES OF NUMPY ARRAYS

"""check dimension"""
print(a.ndim)
#a.ndim means to check dimensions of array
b.ndim
#dimension of the second array
#...............................................................
""" check rows and coloumns"""
print("shape: ",a.shape)
print("size of rows and coloumns:" ,b.shape)
#...............................................................
"""to know what kind of numbers stored"""
print(a.dtype)
print(b.dtype)
#...............................................................
"""To Know size of elements in bytes"""
print(a.itemsize)
print(b.itemsize)
#...............................................................
"""to know total memory in bytes"""
print(a.nbytes)
#...............................................................
"""Total Number of elements"""
print(a.size)
#...............................................................


[1 2 3]
1
shape:  (3,)
size of rows and coloumns: (2, 3)
int32
float64
4
8
12
3


Accessing/Changing speciifc elements,rows,columns etc


In [28]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
#this is the array of 2 rows and 7 coloumns
#.....................................................
"""Access specific element"""
#syntax:a[row_index,column_index]
print(a[1,5])
#.....................................................
"""Access a full row"""
#syntax:a[row_index,:]
print(a[0,:])
#......................................................
"""Access a full column"""
#syntax:a[:,column_index]
print(a[:,2])
#......................................................
"""Fancy Slicing:Select with start:end:step"""
#syntax:a[row_index,start:end:step]
print(a[1,1:-1:3])
#.......................................................
"""change an elemnt"""
#syntax a[row_index,coloumn_index]
a[1,5]=20
print(a)
#........................................................
"""change a full column"""
a[:,2]=[1,2]
#here semi colon represents grabbing entire elements in the row
print(a)




[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[1 2 3 4 5 6 7]
[ 3 10]
[ 9 12]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
